# install.ps1 — Windows installer for the `continuity` CLI.
#
# Mirrors install.sh: installs babashka (if missing), fetches the project
# source, and drops a continuity.cmd shim into a directory it adds to
# the user PATH.
#
# Usage:
#   iwr https://raw.githubusercontent.com/danieltanfh95/continuity-auth/main/install.ps1 -UseBasicParsing | iex
#
# Env vars / parameters (set via $env:CONTINUITY_AUTH_*):
#   CONTINUITY_AUTH_INSTALL_DIR  Default $env:LOCALAPPDATA\continuity-auth
#   CONTINUITY_AUTH_BIN_DIR      Default $env:LOCALAPPDATA\Programs\continuity
#   CONTINUITY_AUTH_REF          Default "main"

$ErrorActionPreference = 'Stop'

$Repo        = 'danieltanfh95/continuity-auth'
$InstallDir  = if ($env:CONTINUITY_AUTH_INSTALL_DIR) { $env:CONTINUITY_AUTH_INSTALL_DIR } else { "$env:LOCALAPPDATA\continuity-auth" }
$BinDir      = if ($env:CONTINUITY_AUTH_BIN_DIR) { $env:CONTINUITY_AUTH_BIN_DIR } else { "$env:LOCALAPPDATA\Programs\continuity" }
$Ref         = if ($env:CONTINUITY_AUTH_REF) { $env:CONTINUITY_AUTH_REF } else { 'main' }

function Log($msg)  { Write-Host "[install] $msg" }
function Die($msg) { Write-Error "[install] ERROR: $msg"; exit 2 }

# -- 1. install babashka if missing --------------------------------------

if (-not (Get-Command bb -ErrorAction SilentlyContinue)) {
    Log "babashka not on PATH; downloading bb for windows-amd64"
    $bbDir = Join-Path $env:LOCALAPPDATA 'babashka'
    New-Item -ItemType Directory -Force -Path $bbDir | Out-Null
    # The bb release artifact name pattern; tracks https://github.com/babashka/babashka/releases.
    $bbReleaseUrl = 'https://github.com/babashka/babashka/releases/latest/download/babashka-windows-amd64.zip'
    $bbZip = Join-Path $bbDir 'bb.zip'
    Invoke-WebRequest -Uri $bbReleaseUrl -OutFile $bbZip -UseBasicParsing
    Expand-Archive -Path $bbZip -DestinationPath $bbDir -Force
    Remove-Item $bbZip
    $env:PATH = "$bbDir;$env:PATH"
    [Environment]::SetEnvironmentVariable('PATH', "$bbDir;$([Environment]::GetEnvironmentVariable('PATH', 'User'))", 'User')
    Log "babashka installed under $bbDir"
}

# -- 2. download project source ------------------------------------------

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Log "fetching continuity-auth@$Ref → $InstallDir"
$tarball = Join-Path $InstallDir '.tarball.zip'
$url     = "https://codeload.github.com/$Repo/zip/refs/heads/$Ref"
try {
    Invoke-WebRequest -Uri $url -OutFile $tarball -UseBasicParsing
} catch {
    $url = "https://codeload.github.com/$Repo/zip/refs/tags/$Ref"
    Invoke-WebRequest -Uri $url -OutFile $tarball -UseBasicParsing
}
Expand-Archive -Path $tarball -DestinationPath $InstallDir -Force
# zipball produces continuity-auth-<sha>/; move its contents up one level.
$extracted = Get-ChildItem -Path $InstallDir -Directory | Where-Object { $_.Name -like 'continuity-auth-*' } | Select-Object -First 1
if ($extracted) {
    Get-ChildItem -Path $extracted.FullName -Force | Move-Item -Destination $InstallDir -Force
    Remove-Item -Recurse -Force $extracted.FullName
}
Remove-Item $tarball -Force

if (-not (Test-Path (Join-Path $InstallDir 'bb.edn'))) { Die "extracted source missing bb.edn" }
if (-not (Test-Path (Join-Path $InstallDir 'bin\continuity'))) { Die "extracted source missing bin/continuity" }

# -- 3. drop shim --------------------------------------------------------

New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$shim = Join-Path $BinDir 'continuity.cmd'
@"
@echo off
rem Auto-generated by continuity-auth install.ps1.
set CONTINUITY_AUTH_INSTALL_DIR_DEFAULT=$InstallDir
if "%CONTINUITY_AUTH_INSTALL_DIR%"=="" set CONTINUITY_AUTH_INSTALL_DIR=%CONTINUITY_AUTH_INSTALL_DIR_DEFAULT%
bb --config "%CONTINUITY_AUTH_INSTALL_DIR%\bb.edn" "%CONTINUITY_AUTH_INSTALL_DIR%\bin\continuity" %*
"@ | Out-File -FilePath $shim -Encoding ASCII

# -- 4. add to user PATH + verify ---------------------------------------

$userPath = [Environment]::GetEnvironmentVariable('PATH', 'User')
if (-not ($userPath -split ';' | Where-Object { $_ -eq $BinDir })) {
    [Environment]::SetEnvironmentVariable('PATH', "$BinDir;$userPath", 'User')
    Log "added $BinDir to user PATH (restart your shell to pick it up)"
}

Log "installed: $shim"
try {
    & $shim --version
} catch {
    Log "WARNING: 'continuity --version' did not run cleanly"
}

Log "done. Try: continuity auth init"
