#!/usr/bin/env bash
#
# install.sh — one-shot installer for the `continuity` CLI.
#
# Does three things, atomically and idempotently:
#   1. Install babashka (via the upstream bb installer) if missing.
#   2. Download the continuity-auth source for the requested ref.
#   3. Drop a `continuity` shim into ~/.local/bin/ (or $CAUTH_BIN_DIR).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/The-Continuity-Project/continuity-auth/main/install.sh | sh
#
# Or, from a local clone:
#   ./install.sh
#
# Env vars:
#   CAUTH_INSTALL_DIR  Where the project source lives. Default
#                      $XDG_DATA_HOME/continuity-auth or ~/.local/share/continuity-auth
#   CAUTH_BIN_DIR      Where the `continuity` shim goes. Default ~/.local/bin
#   CAUTH_REF          Git ref (tag, branch, commit) to install. Default main.
#   CAUTH_SKIP_BB      Set non-empty to skip installing bb (must be on PATH).
#
# Exit codes:
#   0  install succeeded
#   1  precondition failure (curl missing, etc.)
#   2  install step failed

set -eu

REPO="The-Continuity-Project/continuity-auth"
INSTALL_DIR="${CAUTH_INSTALL_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/continuity-auth}"
BIN_DIR="${CAUTH_BIN_DIR:-$HOME/.local/bin}"
REF="${CAUTH_REF:-main}"

log() { printf '[install] %s\n' "$*" >&2; }
die() { printf '[install] ERROR: %s\n' "$*" >&2; exit 2; }

# -- precondition checks --------------------------------------------------

command -v curl >/dev/null 2>&1 || die "curl is required"
command -v tar  >/dev/null 2>&1 || die "tar is required"

# -- 1. install babashka if missing --------------------------------------

if [ -z "${CAUTH_SKIP_BB:-}" ] && ! command -v bb >/dev/null 2>&1; then
  log "babashka not on PATH; installing via the upstream bb installer"
  log "  (set CAUTH_SKIP_BB=1 to skip this step)"
  # The official bb installer drops bb into /usr/local/bin by default,
  # or ~/.local/bin if --dir is given.
  if curl -fsSL https://raw.githubusercontent.com/babashka/babashka/master/install \
        | bash -s -- --dir "$BIN_DIR"; then
    log "babashka installed"
  else
    die "babashka install failed; install manually (e.g. brew install borkdude/brew/babashka) and re-run"
  fi
fi

command -v bb >/dev/null 2>&1 || \
  PATH="$BIN_DIR:$PATH" command -v bb >/dev/null 2>&1 || \
  die "babashka not on PATH after install; check $BIN_DIR"

# -- 2. download project source ------------------------------------------

mkdir -p "$INSTALL_DIR"
log "fetching continuity-auth@${REF} → ${INSTALL_DIR}"
TARBALL_URL="https://codeload.github.com/${REPO}/tar.gz/refs/heads/${REF}"
# heads/<branch> vs tags/<tag>: try heads first; on 404 retry as tag.
if ! curl -fsSL "$TARBALL_URL" -o "${INSTALL_DIR}/.tarball.tar.gz" 2>/dev/null; then
  TARBALL_URL="https://codeload.github.com/${REPO}/tar.gz/refs/tags/${REF}"
  curl -fsSL "$TARBALL_URL" -o "${INSTALL_DIR}/.tarball.tar.gz" \
    || die "could not fetch source for ref ${REF}"
fi

# Strip the top-level continuity-auth-<sha> directory.
tar -xzf "${INSTALL_DIR}/.tarball.tar.gz" -C "$INSTALL_DIR" --strip-components=1
rm -f "${INSTALL_DIR}/.tarball.tar.gz"

[ -f "${INSTALL_DIR}/bb.edn" ] || die "extracted source missing bb.edn — something went wrong"
[ -f "${INSTALL_DIR}/bin/continuity" ] || die "extracted source missing bin/continuity — something went wrong"

# -- 3. drop shim --------------------------------------------------------

mkdir -p "$BIN_DIR"
SHIM="${BIN_DIR}/continuity"
cat > "$SHIM" <<EOF
#!/usr/bin/env bash
# Auto-generated by continuity-auth install.sh.
# Routes the unified continuity CLI through the babashka script under
# CAUTH_INSTALL_DIR (default ~/.local/share/continuity-auth).
set -eu
CAUTH_INSTALL_DIR="\${CAUTH_INSTALL_DIR:-${INSTALL_DIR}}"
exec bb --config "\${CAUTH_INSTALL_DIR}/bb.edn" "\${CAUTH_INSTALL_DIR}/bin/continuity" "\$@"
EOF
chmod +x "$SHIM"

# -- 4. verify ------------------------------------------------------------

log "installed: ${SHIM}"
if ! PATH="$BIN_DIR:$PATH" "$SHIM" --version 2>/dev/null; then
  log "WARNING: 'continuity --version' did not run cleanly — check that ${BIN_DIR} is on PATH"
fi

# Helpful PATH hint.
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;
  *) log "Add ${BIN_DIR} to your PATH:"
     log "  export PATH=\"${BIN_DIR}:\$PATH\"" ;;
esac

log "done. Try: continuity auth init"
