# Homebrew formula for the `continuity` CLI.
#
# Ships as part of a tap: `brew tap danieltanfh95/tap` once the
# tap is registered. Until then, install from the formula path directly:
#   brew install --HEAD --build-from-source ./Formula/continuity.rb
#
# The formula installs:
#   - The continuity-auth source tree (bb.edn + src/ + bin/continuity)
#     under #{prefix}/share/continuity-auth/
#   - A `continuity` shim into #{bin}/ that invokes bb against the bb.edn
#
# Depends on babashka (`borkdude/brew/babashka` formula).

class Continuity < Formula
  desc "Cryptographic device-continuity client for continuity-auth"
  homepage "https://github.com/danieltanfh95/continuity-auth"
  url "https://github.com/danieltanfh95/continuity-auth/archive/refs/tags/v0.1.0.tar.gz"
  # Update sha256 on each release; left placeholder so the formula can
  # bump alongside the tag without touching this file's structure.
  sha256 "PLACEHOLDER_SHA256_TO_BE_FILLED_AT_RELEASE"
  license "MIT"
  head "https://github.com/danieltanfh95/continuity-auth.git", branch: "main"

  depends_on "borkdude/brew/babashka"

  def install
    # Copy the parts of the source tree the CLI actually needs.
    share_dir = share/"continuity-auth"
    share_dir.mkpath
    %w[bb.edn bin src resources].each do |item|
      cp_r item, share_dir if File.exist?(item)
    end

    (bin/"continuity").write <<~SHIM
      #!/usr/bin/env bash
      # Auto-generated by the continuity Homebrew formula.
      set -eu
      CAUTH_INSTALL_DIR="${CAUTH_INSTALL_DIR:-#{share_dir}}"
      exec bb --config "${CAUTH_INSTALL_DIR}/bb.edn" \\
              "${CAUTH_INSTALL_DIR}/bin/continuity" "$@"
    SHIM

    (bin/"continuity").chmod 0755
  end

  test do
    # `--version` must succeed and contain "continuity" in the output.
    assert_match "continuity", shell_output("#{bin}/continuity --version")
  end
end
